# Installation


``` bash
pip3 install torch torchvision
```

In [1]:
import torch
import numpy as np

## Tensors

In [2]:
# Unintiailzed
a = torch.empty(5, 3)
print(a)
print('\n--------------------------------------------\n')
# Randomly intiailzed
b = torch.rand(5, 3)
print(b)
print('\n--------------------------------------------\n')
# Matrix filled zero and of dtype long
c = torch.zeros(5, 3, dtype=torch.long)
print(c)
print('\n--------------------------------------------\n')
# Tensor directly from data
d = torch.tensor([5.5, 3])
print(d)
print('\n--------------------------------------------\n')
# 
e = a.new_ones(5, 3, dtype=torch.double)
print(e)
print('\n--------------------------------------------\n')
f = torch.randn_like(e, dtype=torch.float)    
print(f)
print('\n--------------------------------------------\n')
print(f.size())

tensor([[ 0.0000e+00, -0.0000e+00, -2.2820e+21],
        [-4.6577e-10,  5.6052e-45, -0.0000e+00],
        [-2.2839e+21, -8.5920e+09,  1.8028e+28],
        [ 1.4348e-19,  2.7530e+12,  7.5338e+28],
        [ 1.4569e-19,  1.8888e+31,  3.8063e-39]])

--------------------------------------------

tensor([[0.4750, 0.3843, 0.2148],
        [0.9187, 0.1010, 0.0038],
        [0.2822, 0.9670, 0.5946],
        [0.4977, 0.5415, 0.1846],
        [0.2094, 0.2287, 0.1382]])

--------------------------------------------

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

--------------------------------------------

tensor([5.5000, 3.0000])

--------------------------------------------

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

--------------------------------------------

tensor([[ 0.1389,  0.3795, -0.9001],
        [-0.3488,  1.0108, -0.6430],
        [-1.8868,  0.

## Operations

In [3]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print('x+y\n')
print(x+y)
print('\n--------------------------------------------\n')
print('torch.add(x,y)\n')
print(torch.add(x, y))
print('\n--------------------------------------------\n')
result = torch.empty(5, 3)
print("Before Assign\n")
print(result)
torch.add(x, y, out=result)
print('\n--------------------------------------------\n')
print("After Assign\n")
print(result)

print('\n--------------------------------------------\n')

# adds x to y
print('Raw y data\n')
print(y)
print('\n--------------------------------------------\n')
y.add_(x)
print('Inplacing y data\n')
print(y)

x+y

tensor([[1.7058, 0.8136, 0.3722],
        [0.7308, 1.1851, 1.3569],
        [0.9644, 0.9824, 1.3816],
        [1.2927, 0.2835, 0.9002],
        [1.1363, 1.4954, 1.4070]])

--------------------------------------------

torch.add(x,y)

tensor([[1.7058, 0.8136, 0.3722],
        [0.7308, 1.1851, 1.3569],
        [0.9644, 0.9824, 1.3816],
        [1.2927, 0.2835, 0.9002],
        [1.1363, 1.4954, 1.4070]])

--------------------------------------------

Before Assign

tensor([[                      0.0000,                      -0.0000,
         -2282525340668006498304.0000],
        [                      0.0000,                       0.0000,
                               0.0000],
        [                      0.0000,                       0.0000,
                               0.0000],
        [                      0.0000,                       0.0000,
                               0.0000],
        [                      0.0000,                       0.0000,
                       

In [4]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [5]:
print(z[0,0])
print(z[0,0].item())

tensor(0.7664)
0.7663784027099609


# NumPy Bridge
### Converting a Torch to NumPy

In [8]:
a = torch.ones(5)
print(a)
print('----------------------')
b = a.numpy()
print(b)
print('----------------------')
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
----------------------
[1. 1. 1. 1. 1.]
----------------------
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting Numpy to Torch

In [9]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
